using System;
using UnityEngine;

public class SC_Common_Heroes_Variables : MonoBehaviour {

    [Header("Variables common to all heroes")]
    [Tooltip("Health regenerated by a hero at the start of a turn if he's on a village")]
    public int villageRegen;

    [Tooltip("Amount of health kept by a hero who was saved")]
    public int savedHealthAmount;

    [Tooltip("Amount of health under which a hero becomes berserk")]
    public int berserkTriggerHealth;

    [Tooltip("Amount of relation value required between two heroes for one to go berserk when the other dies")]
    public int berserkTriggerRelation;

    [Tooltip("Damage are multiplied by that amount when the hero is berserker")]
    public float berserkDamageMultiplier;

    [Tooltip("Attack/Defense boosts added for each corresponding relation value with another nearby hero")]
    public RelationBoostValues relationBoostValues;

    [Tooltip("Amount of relation value required between two heroes for one to save the other when he's about to die")]
    public int saveTriggerRelation;

    [Tooltip("Amount of relation value gained by two heroes when one of them kills a unit while nearby the other")]
    public int killRelationValue;

    [Serializable]
    public struct RelationBoostValues {

        public int[] relations;
        public float[] values;

    }

    private void OnValidate () {

        Array.Resize(ref relationBoostValues.values, relationBoostValues.relations.Length);

    }

}
